# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZLInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('zw_url', models.CharField(max_length=50)),
                ('cp_url', models.CharField(max_length=50)),
            ],
        ),
    ]
