# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlinfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
